f = open('/opt/bitvalue-web/app/page.tsx', 'rb')
t = f.read()
f.close()
t = t.replace(b'\xe2\x80\x9c', b'"').replace(b'\xe2\x80\x9d', b'"')
t = t.replace(b'\xe2\x80\x98', b"'").replace(b'\xe2\x80\x99', b"'")
f = open('/opt/bitvalue-web/app/page.tsx', 'wb')
f.write(t)
f.close()
print('OK - comillas corregidas')
